name: Test Action

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 23f3000663@ds.study.iitm.ac.in
        run: echo "Hello, my world!"
